agent {
    data_dir = "c:\\Users\\Lenovo\\Desktop\\Runtime-shield- login\\Runtime-shield-for-agentic-systems\\spire\\agent\\data"
    log_level = "INFO"
    server_address = "127.0.0.1"
    server_port = "8081"
    trust_domain = "runtime-shield"
    insecure_bootstrap = true
    
    # Expose the Workload API via a Named Pipe on Windows
    socket_path = "\\\\.\\pipe\\spire-agent\\public\\api"
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "c:\\Users\\Lenovo\\Desktop\\Runtime-shield- login\\Runtime-shield-for-agentic-systems\\spire\\certs\\agent.key"
            certificate_path = "c:\\Users\\Lenovo\\Desktop\\Runtime-shield- login\\Runtime-shield-for-agentic-systems\\spire\\certs\\agent.crt"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

    # Use Windows Workload Attestor
    WorkloadAttestor "wmi" {
        plugin_data {}
    }
}
