agent {
    data_dir = "/opt/spire/data"
    log_level = "WARN"

    server_address = "spire-server"
    server_port = "8081"

    trust_domain = "runtime-shield"

    insecure_bootstrap = true
}

plugins {

    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "/run/spire/certs/agent.key"
            certificate_path = "/run/spire/certs/agent.crt"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }

}