server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "runtime-shield"
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
}

plugins {

    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
        }
    }

    NodeAttestor "x509pop" {
        plugin_data {
            ca_bundle_path = "/run/spire/certs/ca.crt"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

}